[package]
name = "dackky/fruit-magnet-simulator"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Syscore = "naxious/syscore@1.0.1" # https://naxious.github.io/naxdocs/api/Syscore
Promise = "evaera/promise@^3.1.0"
Timer = "sleitnick/timer@1.1.2"
TableUtil = "sleitnick/table-util@1.2.1"
Cardinal = "remnantsofsiren/cardinal@1.7.8"
react = "jsdotlua/react@17.2.1"
react-roblox = "jsdotlua/react-roblox@17.2.1"